#pragma config(Motor,  motor3,          right,         tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor4,          left,          tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor10,         front,         tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define min(a,b) (((a)<(b))?(a):(b))
#define max(a,b) (((a)>(b))?(a):(b))

task main()
{
	float leftWheelHeading = degreesToRadians(300);
	float rightWheelHeading = degreesToRadians(60);
	float frontWheelHeading = degreesToRadians(180);
	float M = 100;

	while(1){
		int driveY = getJoystickValue(ChA);
		int driveX = getJoystickValue(ChB);
		float driveHeading = atan2(driveY, driveX);
		float driveMagnitude = sqrt( driveX*driveX + driveY*driveY ) / 127;
		float driveRotation = -getJoystickValue(ChC) / 127.0;


		float leftAngle = abs( driveHeading - leftWheelHeading );
		float rightAngle = abs( driveHeading - rightWheelHeading );
		float frontAngle = abs( driveHeading - frontWheelHeading );

		float m = driveMagnitude;
		float leftSpeed = m*cos(leftAngle) + driveRotation;
		float rightSpeed = m*cos(rightAngle) + driveRotation;
		float frontSpeed = m*cos(frontAngle) + driveRotation;

		float maxSpeed = max(max(leftSpeed, rightSpeed), frontSpeed);
		if( maxSpeed > 1.0 ){
			leftSpeed /= maxSpeed;
			rightSpeed /= maxSpeed;
			frontSpeed /= maxSpeed;
		}

		setMotorSpeed( left, M * leftSpeed );
		setMotorSpeed( right, M * rightSpeed );
		setMotorSpeed( front, M * frontSpeed );
	}
}
